/**:
  ros__parameters:
    backward_path_length: 5.0
    forward_path_length: 250.0
    backward_length_buffer_for_end_of_lane: 5.0
    backward_length_buffer_for_end_of_pull_over: 5.0
    backward_length_buffer_for_end_of_pull_out: 5.0
    minimum_lane_change_length: 8.0
    minimum_pull_over_length: 16.0
    drivable_area_resolution: 0.1
    drivable_lane_forward_length: 50.0
    drivable_lane_backward_length:  5.0
    drivable_lane_margin: 3.0
    drivable_area_margin: 6.0
    refine_goal_search_radius_range: 7.5
    intersection_search_distance: 30.0
    min_stop_distance: 5.0
    stop_time: 0.5
    hysteresis_buffer_distance: 1.5
    lane_change_prepare_duration: 0.55
    lane_changing_duration: 6.25
    lane_change_finish_judge_buffer: 0.5
    minimum_lane_change_velocity: 15.0
    prediction_duration: 8.0
    prediction_time_resolution: 0.5
    static_obstacle_velocity_thresh: 1.5
    maximum_deceleration: 1.0
    enable_abort_lane_change: false
    enable_collision_check_at_prepare_phase: false
    use_predicted_path_outside_lanelet: false
    use_all_predicted_path: false
    enable_blocked_by_obstacle: false
    lane_change_search_distance: 30.0

