/**:
  ros__parameters:

    # Latitude of map_origin
    # latitude: 40.816617984672746
    # longitude: 29.360491808334285
    SanFrancisco.osm:
      latitude: 37.79318886541425
      longitude: -122.39984922532807
    BorregasAve.osm:
      latitude: 37.416910205894
      longitude: -122.016032188409
    soongsil_map_test.osm:
      latitude: 0.0
      longitude: 0.0
    kcity.osm:
      latitude: 0.0
      longitude: 0.0
    