/**:
  ros__parameters:
    wheel_radius: 0.37
    wheel_width: 0.27
    wheel_base: 2.734 # between front wheel center and rear wheel center
    wheel_tread: 1.571 # between left wheel center and right wheel center
    front_overhang: 1.033 # between front wheel center and vehicle front
    rear_overhang: 1.021 # between rear wheel center and vehicle rear
    left_overhang: 0.3135 # between left wheel center and vehicle left
    right_overhang: 0.3135 # between right wheel center and vehicle right
    # vehicle_height: 1.662
    vehicle_height: 1.962
    max_steer_angle: 0.53 # [rad]
