/**:
  ros__parameters:
    engine_file:   "/workspaces/isaac_ros-dev/src/ichthus_tensorrt_yolo/data/yolov4-csp.trt"
    label_file:   "/workspaces/isaac_ros-dev/src/ichthus_tensorrt_yolo/data/coco.names"
    name : ichthus_trt_yolo_normal
    input_topic : "/right_raw"
    output_topic : "/right_rois0"
    mode : "FP16"
    yolo_version : "yolov4"
    BATCH_SIZE:    1
    INPUT_CHANNEL: 3
    IMAGE_WIDTH:   512
    IMAGE_HEIGHT:  512
    image_order:   "BCHW"
    channel_order: "BGR"
    obj_threshold: 0.4
    nms_threshold: 0.45
    agnostic:      False
    strides:       [8, 16, 32]
    num_anchors:   [3,  3,  3]
    anchors:       [12, 16, 
                    19, 36, 
                    40, 28, 
                    36, 75, 
                    76, 55, 
                    72, 146, 
                    142, 110, 
                    192, 243, 
                    459, 401]
    img_mean:      [ 0.0, 0.0, 0.0 ]
    img_std:       [ 1.0, 1.0, 1.0 ]
    alpha:         255.0
    resize:        "keep_ratio"
